name: CI-CD Linux Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest || echo "No tests found"

    - name: Copy project files to Linux VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.LINUX_VM_IP }}
        username: ${{ secrets.LINUX_VM_USER }}
        key: ${{ secrets.LINUX_VM_KEY }}
        source: "./"
        target: "~/flaskapp"

    - name: Restart Flask App
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.LINUX_VM_IP }}
        username: ${{ secrets.LINUX_VM_USER }}
        key: ${{ secrets.LINUX_VM_KEY }}
        script: |
          # Stop any old Flask process
          pkill -f "python3 app.py" || true
          
          # Start Flask app in background and redirect logs
          nohup /usr/bin/python3 /home/${{ secrets.LINUX_VM_USER }}/flaskapp/app.py > /home/${{ secrets.LINUX_VM_USER }}/flaskapp/log.txt 2>&1 &
